project:
  type: book
  output-dir: docs

book:
  title: "Time Series Analysis"
  subtitle: "Lecture Notes"
  author: "V. Lyubchich and Y. R. Gel"
  date: today
  date-format: iso
  number-sections: true
  # repo-url: https://github.com/vlyubchich/lectures_ts/
  # repo-actions: [edit]
  # downloads: [pdf, epub]
  # sharing: [twitter, facebook]
  reader-mode: true
  sidebar:
    search: true
  chapters:
    - index.qmd
    - l01_regression.qmd
    - l02_tsintro.qmd
    - l03_smoothing.qmd
    - l04_arma.qmd
    - software.qmd
    - references.qmd

bibliography:
    - references.bib
    - refpackages.bib
csl: springer-basicVL.csl

format:
  html:
    code-fold: true
    theme: cosmo
    fig-width: 8
    fig-height: 6
  pdf:
    documentclass: scrbook
    fig-width: 8
    fig-height: 6

knitr:
  opts_chunk:
    collapse: false
    message: false
    warning: false
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

