project:
  type: book
  output-dir: docs

book:
  title: "Time Series Analysis"
  subtitle: "Lecture Notes"
  author: "Vyacheslav Lyubchich and Yulia R. Gel"
  date: "2022-12-31"
  date-format: iso
  number-sections: true
  sidebar:
    search: true
  repo-url: https://github.com/vlyubchich/lectures_ts/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - l03_smoothing.qmd
    - references.qmd

bibliography: references.bib
csl: springer-basicVL.csl

format:
  html:
    code-fold: true
    theme: cosmo
    fig-width: 8
    fig-height: 6
  pdf:
    documentclass: scrbook
    fig-width: 8
    fig-height: 6

knitr:
  opts_chunk:
    collapse: false
    message: false
    warning: false
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

